# 1.Create a 3X3X3 array with random values.

In [3]:
import numpy as np


random_array = np.random.rand(3, 3, 3)

print(random_array)


[[[0.11115554 0.0229299  0.69296655]
  [0.8815573  0.08508831 0.98813103]
  [0.00160499 0.48574891 0.29978733]]

 [[0.94468979 0.58865776 0.134696  ]
  [0.46521928 0.60992446 0.27405449]
  [0.34416823 0.65972683 0.04203869]]

 [[0.49632876 0.7170551  0.72590395]
  [0.8297553  0.52698127 0.92549104]
  [0.25407052 0.35527776 0.24491469]]]


# 2.Create a 5X5 matrix with values 1,2,3,4 just below the diagonal

In [4]:
import numpy as np
matrix = np.zeros((5, 5))
values_below_diagonal = np.array([1, 2, 3, 4])
np.fill_diagonal(matrix[1:], values_below_diagonal)

print(matrix)


[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


# 3.Create a 8X8 matrix and fill it with a checkerboard pattern.

In [6]:
import numpy as np
matrix = np.zeros((8, 8))

matrix[::2, ::2] = 1
matrix[1::2, 1::2] = 1

print(matrix)


[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


# 4.Normalize a 5X5 radnom matrix.

In [7]:
import numpy as np

random_matrix = np.random.rand(5, 5)

mean = np.mean(random_matrix)
std_dev = np.std(random_matrix)

normalized_matrix = (random_matrix - mean) / std_dev

print("Original Matrix:")
print(random_matrix)
print("\nNormalized Matrix:")
print(normalized_matrix)


Original Matrix:
[[0.08596803 0.79029732 0.4301073  0.24279361 0.12971678]
 [0.26113308 0.76518524 0.94626519 0.70705741 0.8130395 ]
 [0.80316029 0.49011984 0.69879817 0.41564009 0.73010299]
 [0.9130032  0.03426773 0.41437711 0.13222057 0.05235433]
 [0.34414634 0.39533453 0.79370315 0.14018632 0.87328125]]

Normalized Matrix:
[[-1.36913881  0.98217067 -0.2202757  -0.84559751 -1.22308942]
 [-0.78437363  0.89833735  1.50284866  0.70428534  1.05809243]
 [ 1.02511201 -0.01993185  0.67671297 -0.26857254  0.78121993]
 [ 1.3918079  -1.54173337 -0.27278885 -1.21473087 -1.48135367]
 [-0.50724492 -0.33635995  0.99354059 -1.18813826  1.25920149]]


# 5.How to find common values between two arrays?

In [9]:
import numpy as np


arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([3, 4, 5, 6, 7])


common_values = np.intersect1d(arr1, arr2)

print("Common values:", common_values)


Common values: [3 4 5]


# 6. How to get the dates of yesterday,today and tommorow?

In [10]:
import numpy as np
from datetime import datetime, timedelta
today = datetime.now()
yesterday = today - timedelta(days=1)
tomorrow = today + timedelta(days=1)
dates = np.array([yesterday, today, tomorrow])
print("Yesterday:", dates[0])
print("Today:", dates[1])
print("Tomorrow:", dates[2])


Yesterday: 2023-09-20 16:47:13.437586
Today: 2023-09-21 16:47:13.437586
Tomorrow: 2023-09-22 16:47:13.437586


# 7.Consider two random array A and B and check if they are equal.

In [12]:
import numpy as np


A = np.random.rand(3, 3)
B = np.random.rand(3, 3)


are_equal = np.array_equal(A, B)
if are_equal:
    print("Arrays A and B are equal")
else :
     print("Arrays A and B are not equal")


Arrays A and B are not equal


# 8.Create a random vector of size 10 and replace the maximum value by 0.

In [19]:
import numpy as np

random_vector = np.random.rand(10)

print("Original vector:")
print(random_vector)

max_value = np.max(random_vector)
random_vector[random_vector == max_value] = 0
print("afte replacing max value with 0 :")
print(random_vector)


Original vector:
[0.61083615 0.2778777  0.17609595 0.34748226 0.63790757 0.8824375
 0.55095674 0.01569833 0.9447535  0.72294988]
afte replacing max value with 0 :
[0.61083615 0.2778777  0.17609595 0.34748226 0.63790757 0.8824375
 0.55095674 0.01569833 0.         0.72294988]


# 9.How to print all the values of an array?

In [20]:
import numpy as np


arr = np.array([1, 2, 3, 4, 5])

print("All values of an array :",arr)

All values of an array : [1 2 3 4 5]


# 10.Subtract the mean of each row of a matrix.

In [ ]:
import numpy as np


matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])


row_means = np.mean(matrix, axis=1)


normalized_matrix = matrix - row_means[:, np.newaxis]

print("Original Matrix:")
print(matrix)

print("\nMean of each row:")
print(row_means)

print("\nMatrix after subtracting row means:")
print(normalized_matrix)


In [ ]:
11.COnsider a given vector, how to add 1 to each element indexed by a second vector(be careful with replaced indices)?

In [23]:
import numpy as np


vector = np.array([44, 78, 35, 45, 584])


indices = np.array([1, 3])


vector[indices] += 1

print("Original vector:")
print(vector)


Original vector:
[ 44  79  35  46 584]


# 12.How to get the diagonal of a dot product

In [24]:
import numpy as np


matrix1 = np.random.rand(3, 3)
matrix2 = np.random.rand(3, 3)


dot_product = np.dot(matrix1, matrix2)


diagonal_elements = np.diag(dot_product)


print("dot_product is :",dot_product)

print("\nDiagonal elements of the dot product:",diagonal_elements)



dot_product is : [[0.67324515 0.60354138 0.79162596]
 [0.22067214 0.25087635 0.29812252]
 [1.08160694 1.03010533 1.22673321]]

Diagonal elements of the dot product: [0.67324515 0.25087635 1.22673321]


# 13.How to find the most frequent value in an array?


In [28]:
import numpy as np


array = np.array([1, 2, 3, 2, 2, 3, 4, 3, 3])


count = np.bincount(array)



most_frequent_value = np.argmax(count)

print("Array:", array)
print("Most frequent value:", most_frequent_value)


Array: [1 2 3 2 2 3 4 3 3]
Most frequent value: 3


# 14.How to get the n largest values of n array

In [29]:
import numpy as np


array = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5])


n = 3


n_largest_values = np.partition(array, -n)[-n:]

print("Array:", array)
print(f"{n} largest values:", n_largest_values)


Array: [3 1 4 1 5 9 2 6 5 3 5]
3 largest values: [5 6 9]


# 15.How to create a record array from a regular array?


In [33]:
import numpy as np


r1= np.array([(25, 'sriram', 22), 
                          (56, 'surya', 55), 
                          (5, 'kumar', 44)],
                         dtype=[('id', int), ('name', 'U10'), ('age', int)])


r2 = np.core.records.fromarrays(r1.transpose(), 
                                           names='id, name, age')

print("Regular Array:")
print(r1)

print("\nRecord Array:")
print(r2)


Regular Array:
[(25, 'sriram', 22) (56, 'surya', 55) ( 5, 'kumar', 44)]

Record Array:
((25, 'sriram', 22), (56, 'surya', 55), (5, 'kumar', 44))


# 16.How to swap two rows of an array?

In [36]:
import numpy as np

array = np.array([[65, 23, 463],
                  [5421, 55, 26],
                  [447, 568, 29]])

print("Original array:")
print(array)
array[[0, 1]] = array[[1, 0]]

print("\nArray after swapping ")
print(array)


Original array:
[[  65   23  463]
 [5421   55   26]
 [ 447  568   29]]

Array after swapping 
[[5421   55   26]
 [  65   23  463]
 [ 447  568   29]]


# 17.Write a python code to reshape to the next dimension of numpy array?
x=np.array([[23,34,121],[23,22,67],[686,434,123]])

In [37]:
import numpy as np


x = np.array([[23, 34, 121], [23, 22, 67], [686, 434, 123]])


total_elements = x.size


next_dimension = int(np.ceil(total_elements ** (1 / 3)))


reshaped_array = x.reshape((next_dimension, -1))

print("Original array:")
print(x)

print("\nReshaped array to the next dimension:")
print(reshaped_array)


Original array:
[[ 23  34 121]
 [ 23  22  67]
 [686 434 123]]

Reshaped array to the next dimension:
[[ 23  34 121]
 [ 23  22  67]
 [686 434 123]]
